#define a int
#define aa main
#define aaa (
#define aaaa )
#define aaaaa {
#define aaaaaa while
#define aaaaaaa 1
#define aaaaaaaa printf
#define aaaaaaaaa "%s"
#define aaaaaaaaaa ,
#define aaaaaaaaaaa "a"
#define aaaaaaaaaaaa ;
#define aaaaaaaaaaaaa return
#define aaaaaaaaaaaaaa 0
#define aaaaaaaaaaaaaaa }
